### PR TITLE
Use slf4j implementation only in test; add slf4j-api dependency

### LINKED ISSUE #47: JS-Engine should not provide an SLF4J implementation
If you look at the libraryDependencies, slf4j-simple is packaged with js-engine:

https://github.com/typesafehub/js-engine/blob/master/build.sbt#L13

This is causing conflicts when a competing SFL4J implementation is loaded into a project:

https://groups.google.com/d/msgid/play-framework/bb07a3fa-891c-4c1a-b74d-9faa323eb241%40googlegroups.com.

### PR DESCRIPTION
**Pull request by mckinley-olsen-oc**
Fixes #47

### CODE REVIEW

**Comment by mckinley-olsen-oc** [comment]
I believe the failing test (The Trireme engine should not leak threads) is non-deterministic
On my fork of the project, with the ability to rerun the build, I have seen it fail and pass on the rebuild

Is it possible to have the build rerun for this pull request, and with a passing one get this change merged?

**Comment by benmccann** [comment]
This is a duplicate of https://github.com/typesafehub/js-engine/pull/48

**Comment by mckinley-olsen-oc** [comment]
In some sense, though this is focused on changing a particular dependency, which I hoped would be less risky and more likely to get the merged

**Comment by huntc** [comment]
Tests failing

**Comment by benmccann** [comment]
This can be closed now that #48 has been merged

**Pull request closed without merging**
